name: Source
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  prepare-source-image:
    runs-on: ubuntu-latest
    steps:
    - name: get timestamp 
      id: time
      run: echo "::set-output name=time::$(date -u)"
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: build source image
      run : |
        docker login -u ${{ secrets.DOCKER_REPO_USER }} -p ${{ secrets.DOCKER_REPO_PASSWORD }} workstation.thinkmay.net
        docker build sidecar/auth -t workstation.thinkmay.net/mount2web:${{ steps.date.outputs.date }}
        docker tag workstation.thinkmay.net/mount2web:${{ steps.date.outputs.date }} workstation.thinkmay.net/mount2web:latest

        docker push workstation.thinkmay.net/mount2web:${{ steps.date.outputs.date }}
        docker push workstation.thinkmay.net/mount2web:latest